/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psbd.projekt.panes;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import psbd.projekt.utils.MySql;

/**
 *
 * @author Michal
 */
public class HotelNiezre extends javax.swing.JPanel {

    int id_rezerwacji;
    Niezrealizowane parentDialog;
    ArrayList<PokojNiezre> pokoje = new ArrayList<>();
    JPanel p = new JPanel();
            
    /**
     * Creates new form HotelNiezre
     */
    public HotelNiezre(int id_rezerwacji, String nazwa, int liczbaGw, Niezrealizowane parentDialog) {
        initComponents();
        this.id_rezerwacji = id_rezerwacji;
        this.parentDialog = parentDialog;
        lblNrRezerwacji.setText("Numer rezerwacji:" + id_rezerwacji);
        lblNazwa.setText(nazwa);
        String str = "";
        for(int i = 0; i<liczbaGw;++i){
            str += "*";
        }
        lblIoscGwiazdek.setText(str);
    }

    public int getIdRezerwacji() {
        return id_rezerwacji;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblNazwa = new javax.swing.JLabel();
        lblIoscGwiazdek = new javax.swing.JLabel();
        lblNrRezerwacji = new javax.swing.JLabel();

        jButton1.setText("Anuluj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblNazwa.setText("Nazwa");

        lblIoscGwiazdek.setText("***");

        lblNrRezerwacji.setText("Rezerwacja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNazwa)
                        .addGap(18, 18, 18)
                        .addComponent(lblIoscGwiazdek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(lblNrRezerwacji)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblNazwa)
                    .addComponent(lblIoscGwiazdek)
                    .addComponent(lblNrRezerwacji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz usunąć rezerwacje?", "Uwaga!", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            MySql.getInstance().anulujRezerwacje(id_rezerwacji);
            parentDialog.updateDialog();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIoscGwiazdek;
    private javax.swing.JLabel lblNazwa;
    private javax.swing.JLabel lblNrRezerwacji;
    // End of variables declaration//GEN-END:variables

    void addPokoj(int standard) {
        PokojNiezre pn = new PokojNiezre();
        pokoje.add(pn);
    }

    void renderuj() {
        int size = pokoje.size();
        p.setLayout(new GridLayout(size, 1));
        for(int i =0; i<size;++i){
            p.add(pokoje.get(i));
        }
        jScrollPane1.setViewportView(p);
        jScrollPane1.validate();
        jScrollPane1.repaint();
    }
}
