/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psbd.projekt.panes;

import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import psbd.projekt.utils.MySql;

/**
 *
 * @author Michal
 */
public class Niezrealizowane extends javax.swing.JPanel {

    ArrayList<HotelNiezre> nieRezerwacje = new ArrayList<HotelNiezre>();
    JPanel myView = new JPanel();

    /**
     * Creates new form Niezrealizowane
     */
    public Niezrealizowane() {
        initComponents();

//        int size = pokoje.size();
//        p.setLayout(new GridLayout(size, 1));
//        for (int i = 0; i < size; ++i) {
//            p.add(pokoje.get(i));
//        }
//        jspPokoje.setViewportView(p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldNr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        jLabel1.setText("Numer rezerwacji:");

        jLabel2.setText("Numer dowodu:");

        jButton1.setText("Szukaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Wszystkie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNr, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        updateDialog();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldNr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public void updateDialog() {
        nieRezerwacje.clear();
        int nrRez = 0;
        try {
            nrRez = Integer.parseInt(fieldNr.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Numer rejestracji powinien być liczbą!",
                    "Błędna data!",
                    JOptionPane.ERROR_MESSAGE);
        }
        ArrayList<ArrayList<Object>> rekordyrekordy = MySql.getInstance().getNiezrealizowane(nrRez);
        int sizeRekordy = rekordyrekordy.size();
        for (int i = 0; i < sizeRekordy; ++i) {
            int sizeArray = nieRezerwacje.size();
            boolean dodane = false;
            for (int j = 0; j < sizeArray; ++j) {
                if (nieRezerwacje.get(j).getIdRezerwacji() == (int) rekordyrekordy.get(i).get(0)) {
                    nieRezerwacje.get(j).addPokoj((int) rekordyrekordy.get(i).get(2));
                    dodane = true;
                    break;
                }
            }
            if (!dodane) {
                //        pokoj.add(rs.getInt("id_rezerwacji"));
//        pokoj.add(rs.getString("nazwa"));
//        pokoj.add(rs.getString("standard"));
//        pokoj.add(rs.getString("liczba_gwiazdek"));
//        pokoj.add(rs.getString("id_hotelu"));
                HotelNiezre nowe = new HotelNiezre((int) rekordyrekordy.get(i).get(0), (String) rekordyrekordy.get(i).get(1), (int) rekordyrekordy.get(i).get(3), this);
                nowe.addPokoj((int) rekordyrekordy.get(i).get(2));
                nieRezerwacje.add(nowe);
            }
        }
        int nieZreSize = nieRezerwacje.size();
        myView.removeAll();
        myView.setLayout(new GridLayout(nieZreSize, 1));
        for (int i = 0; i < nieZreSize; ++i) {
            nieRezerwacje.get(i).renderuj();
            myView.add(nieRezerwacje.get(i));
        }
        jScrollPane1.setViewportView(myView);
        jScrollPane1.validate();
        jScrollPane1.repaint();
    }
}
