/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psbd.projekt;

import java.awt.GridLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import psbd.projekt.classes.Klient;
import psbd.projekt.dialogs.Konto;
import psbd.projekt.dialogs.LoginDialog;
import psbd.projekt.model.Hotel;
import psbd.projekt.model.SiecHoteli;
import psbd.projekt.utils.MySql;

/**
 *
 * @author Michal
 */
public class MainWindow extends javax.swing.JFrame implements WindowListener {

    JPanel p = new JPanel();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        initWyszukiwarke();
        SiecHoteli.getInstance().setParent(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZalogowanyUzytkownik = new javax.swing.JLabel();
        btnZaloguj = new javax.swing.JButton();
        btnWyloguj = new javax.swing.JButton();
        btnEdytuj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldMiejsce = new javax.swing.JTextField();
        cbDzienOd = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbDzienDo = new javax.swing.JComboBox();
        cbMiesiacOd = new javax.swing.JComboBox();
        cbRokOd = new javax.swing.JComboBox();
        cbMiesiacDo = new javax.swing.JComboBox();
        cbRokDo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spinnerDor = new javax.swing.JSpinner();
        spinnerDzie = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblZalogowanyUzytkownik.setText("Zalogowany użytkownik:");

        btnZaloguj.setText("Zaloguj");
        btnZaloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZalogujActionPerformed(evt);
            }
        });

        btnWyloguj.setText("Wyloguj");
        btnWyloguj.setEnabled(false);
        btnWyloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWylogujActionPerformed(evt);
            }
        });

        btnEdytuj.setText("Konto");
        btnEdytuj.setEnabled(false);
        btnEdytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdytujActionPerformed(evt);
            }
        });

        jLabel1.setText("Miejsce:");

        jLabel3.setText("Data przyjazdu");

        jLabel4.setText("Data wyjazdu");

        jLabel2.setText("Liczba gości");

        jLabel5.setText("Dorośli:");

        jLabel6.setText("Dzieci:");

        jButton1.setText("Szukaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblZalogowanyUzytkownik, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(btnZaloguj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnWyloguj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdytuj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDzienOd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMiesiacOd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbRokOd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbDzienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbMiesiacDo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4)
                                .addComponent(cbRokDo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spinnerDor))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(spinnerDzie)))
                            .addComponent(jButton1)
                            .addComponent(fieldMiejsce, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblZalogowanyUzytkownik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnZaloguj)
                        .addComponent(btnWyloguj)
                        .addComponent(btnEdytuj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldMiejsce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDzienOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMiesiacOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRokOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDzienDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMiesiacDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRokDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spinnerDor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(spinnerDzie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(160, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZalogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZalogujActionPerformed
        LoginDialog loginDlg = new LoginDialog(this, true);
        loginDlg.setVisible(true);

        if (loginDlg.isSucceeded()) {
            zaloguj();
        }
    }//GEN-LAST:event_btnZalogujActionPerformed

    private void btnWylogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWylogujActionPerformed
        wyloguj();
    }//GEN-LAST:event_btnWylogujActionPerformed

    private void btnEdytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdytujActionPerformed

        
        Konto KontoDlg = new Konto(this, true);
        KontoDlg.setVisible(true);
//        int msg = edytujKontoDlg.getReturnCode();
//        switch (msg) {
//            case 1:
//                Klient klient = Klient.getInstance();
//                String imie = klient.getImie();
//                String nazwisko = klient.getNazwisko();
//                lblZalogowanyUzytkownik.setText("Zalogowany użytkownik: " + klient.getNazwisko() + " " + klient.getImie());
//                break;
//            case 2:
//                wyloguj();
//                break;
//        }

    }//GEN-LAST:event_btnEdytujActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        wyszukaj();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private void drawHotele() {
        Hotel[] hotele = SiecHoteli.getInstance().getHotele();
        int size = hotele.length;
        p.setLayout(new GridLayout(size, 1));
        for (int i = 0; i < size; ++i) {
            hotele[i].drawPokoje();
            p.add(hotele[i]);
        }
        jScrollPane1.setViewportView(p);
    }

    private void zaloguj() {
        btnWyloguj.setEnabled(true);
        btnEdytuj.setEnabled(true);
        btnZaloguj.setEnabled(false);
        Klient klient = Klient.getInstance();
        lblZalogowanyUzytkownik.setText("Zalogowany użytkownik: " + klient.getNazwisko() + " " + klient.getImie());
    }

    private void wyloguj() {
        btnWyloguj.setEnabled(false);
        btnEdytuj.setEnabled(false);
        btnZaloguj.setEnabled(true);
        Klient.getInstance().clearUser();
        lblZalogowanyUzytkownik.setText("Zalogowany użytkownik: -");
    }

    public void wyszukaj() {
        p.removeAll();
        p.revalidate();
        p.repaint();   // This is required in some cases
        SiecHoteli.getInstance().clear();
        int iloscOsob = (int)spinnerDor.getValue() + (int)spinnerDzie.getValue();
        String miejsce = fieldMiejsce.getText();
        Date dataOd = new Date(
                Integer.parseInt((String) cbRokOd.getSelectedItem()) - 1900,
                Integer.parseInt((String) cbMiesiacOd.getSelectedItem()) - 1,
                Integer.parseInt((String) cbDzienOd.getSelectedItem())
        );
        Date dataDo = new Date(
                Integer.parseInt((String) cbRokDo.getSelectedItem()) - 1900,
                Integer.parseInt((String) cbMiesiacDo.getSelectedItem()) - 1,
                Integer.parseInt((String) cbDzienDo.getSelectedItem())
        );
        if(dataDo.before(dataOd)){
            JOptionPane.showMessageDialog(null,
                    "Data przyjazdu musi byc przed dacie wyjazdu!",
                    "Błędna data!",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        MySql.getInstance().wyszukajPokoje(iloscOsob, miejsce, dataOd, dataDo);
        drawHotele();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdytuj;
    private javax.swing.JButton btnWyloguj;
    private javax.swing.JButton btnZaloguj;
    private javax.swing.JComboBox cbDzienDo;
    private javax.swing.JComboBox cbDzienOd;
    private javax.swing.JComboBox cbMiesiacDo;
    private javax.swing.JComboBox cbMiesiacOd;
    private javax.swing.JComboBox cbRokDo;
    private javax.swing.JComboBox cbRokOd;
    private javax.swing.JTextField fieldMiejsce;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblZalogowanyUzytkownik;
    private javax.swing.JSpinner spinnerDor;
    private javax.swing.JSpinner spinnerDzie;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e) {
        MySql.getInstance().closeConnection();
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void initWyszukiwarke() {
        List<String> dzien = new ArrayList<String>();
        for (int i = 1; i < 32; i++) {
            dzien.add("" + i);
        }
        List<String> miesiac = new ArrayList<String>();
        for (int i = 1; i < 13; i++) {
            miesiac.add("" + i);
        }
        int year = Calendar.getInstance().get(Calendar.YEAR);

        List<String> rok = new ArrayList<String>();
        for (int i = 0; i < 121; i++) {
            int rok2 = year - i;
            rok.add("" + rok2);
        }

        cbDzienDo.setModel(new DefaultComboBoxModel(dzien.toArray()));
        cbDzienOd.setModel(new DefaultComboBoxModel(dzien.toArray()));

        cbMiesiacDo.setModel(new DefaultComboBoxModel(miesiac.toArray()));
        cbMiesiacOd.setModel(new DefaultComboBoxModel(miesiac.toArray()));

        cbRokDo.setModel(new DefaultComboBoxModel(rok.toArray()));
        cbRokOd.setModel(new DefaultComboBoxModel(rok.toArray()));
        
        cbDzienOd.setToolTipText("Dzień");
        cbMiesiacOd.setToolTipText("Miesiąc");
        cbRokOd.setToolTipText("Rok");
        
        cbDzienDo.setToolTipText("Dzień");
        cbMiesiacDo.setToolTipText("Miesiąc");
        cbRokDo.setToolTipText("Rok");
    }
}
